### ISSUE TITLE
Add team whitelist

### ISSUE THREAD

**Issue by humanfriend22** [cookie-jar-smp/tpa-home-plugin#2]
I think there should be a way to allow teleportation so that people can't just teleport to whoever they want. 

We can implement it like so:

1. When a teleport request is sent to another player, it should ask the target player to confirm. (with `/confirm` or something of the sort )
2. It should then either wait for 5 seconds (or any other suitable time) & reject the teleportation or allow it if `/confirm` was sent.

**Comment by varun31415** [comment]
Implementation already exists
